# Generated by Django 4.2.24 on 2025-09-20 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manufacturing', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockLedger',
            fields=[
                ('ledger_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_change', models.DecimalField(decimal_places=2, help_text='Quantity changed (+ for addition, - for consumption)', max_digits=10)),
                ('stock_before', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_after', models.DecimalField(decimal_places=2, max_digits=10)),
                ('movement_type', models.CharField(choices=[('MO_CONSUMPTION', 'Manufacturing Order - Component Consumption'), ('MO_PRODUCTION', 'Manufacturing Order - Finished Good Production'), ('MANUAL_IN', 'Manual Stock Addition'), ('MANUAL_OUT', 'Manual Stock Removal'), ('ADJUSTMENT', 'Stock Adjustment'), ('INITIAL_STOCK', 'Initial Stock Entry')], max_length=20)),
                ('reference_number', models.CharField(blank=True, help_text='MO number, adjustment ref, etc.', max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the transaction')),
                ('transaction_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='products.product')),
                ('related_mo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='manufacturing.manufacturingorder')),
            ],
            options={
                'ordering': ['-transaction_time'],
                'indexes': [models.Index(fields=['product'], name='inventory_s_product_bcb5e0_idx'), models.Index(fields=['movement_type'], name='inventory_s_movemen_553342_idx'), models.Index(fields=['transaction_time'], name='inventory_s_transac_3af8b4_idx'), models.Index(fields=['related_mo'], name='inventory_s_related_83f088_idx')],
            },
        ),
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('adjustment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('adjustment_number', models.CharField(max_length=50, unique=True)),
                ('expected_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('actual_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('adjustment_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('adjustment_type', models.CharField(choices=[('COUNT', 'Physical Count Adjustment'), ('DAMAGE', 'Damaged Goods'), ('LOSS', 'Lost/Missing Items'), ('FOUND', 'Found Items'), ('CORRECTION', 'Data Correction')], max_length=20)),
                ('reason', models.TextField(help_text='Reason for the adjustment')),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_adjustments', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_adjustments', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='products.product')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product'], name='inventory_s_product_bb1a16_idx'), models.Index(fields=['is_approved'], name='inventory_s_is_appr_7a84ab_idx')],
            },
        ),
    ]
