# Generated by Django 4.2.24 on 2025-09-20 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('MANAGER', 'Manufacturing Manager'), ('OPERATOR', 'Shop Floor Operator')], default='OPERATOR', max_length=20),
        ),
    ]
