# Generated by Django 4.2.24 on 2025-09-20 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkCenter',
            fields=[
                ('work_center_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Name (e.g., 'Assembly Line 1', 'Paint Floor')", max_length=100)),
                ('code', models.CharField(help_text="Short code (e.g., 'ASM1', 'PAINT')", max_length=20, unique=True)),
                ('cost_per_hour', models.DecimalField(decimal_places=2, default=0.0, help_text='Costing rate for this work center (per hour)', max_digits=10)),
                ('capacity_hours_per_day', models.DecimalField(decimal_places=2, default=8.0, help_text='Available working hours per day', max_digits=8)),
                ('description', models.TextField(blank=True, help_text='Description of the work center')),
                ('location', models.CharField(blank=True, help_text='Physical location', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this work center is operational')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workcenters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['code'], name='workcenters_code_cf34c1_idx'), models.Index(fields=['is_active'], name='workcenters_is_acti_8bad7c_idx')],
            },
        ),
    ]
