# Generated by Django 4.2.23 on 2025-09-20 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workcenters', '0001_initial'),
        ('bom', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManufacturingOrder',
            fields=[
                ('mo_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mo_number', models.CharField(help_text='Human-readable MO number', max_length=50, unique=True)),
                ('quantity_to_produce', models.PositiveIntegerField(help_text='Target quantity of finished product')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('CONFIRMED', 'Confirmed'), ('IN_PROGRESS', 'In Progress'), ('DONE', 'Done'), ('CANCELED', 'Canceled')], default='DRAFT', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=10)),
                ('scheduled_start_date', models.DateField(help_text='Planned start date for production')),
                ('scheduled_end_date', models.DateField(blank=True, null=True)),
                ('actual_start_date', models.DateTimeField(blank=True, null=True)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('quantity_produced', models.PositiveIntegerField(default=0, help_text='Actual quantity produced')),
                ('notes', models.TextField(blank=True, help_text='MO notes or special instructions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(help_text='Manager responsible for this order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_manufacturing_orders', to=settings.AUTH_USER_MODEL)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manufacturing_orders', to='bom.bom')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_manufacturing_orders', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manufacturing_orders', to='products.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('wo_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('wo_number', models.CharField(help_text='Human-readable WO number', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Operation name', max_length=100)),
                ('sequence', models.PositiveIntegerField(help_text='Order in the manufacturing process')),
                ('estimated_duration_minutes', models.PositiveIntegerField(help_text='Estimated completion time')),
                ('actual_duration_minutes', models.PositiveIntegerField(default=0, help_text='Actual time taken')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('CANCELED', 'Canceled')], default='PENDING', max_length=20)),
                ('scheduled_start_date', models.DateTimeField(blank=True, null=True)),
                ('actual_start_date', models.DateTimeField(blank=True, null=True)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Work order notes, instructions, or issues')),
                ('quality_notes', models.TextField(blank=True, help_text='Quality control notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bom_operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='bom.bomoperation')),
                ('mo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='manufacturing.manufacturingorder')),
                ('operator', models.ForeignKey(blank=True, help_text='Operator assigned to this task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_work_orders', to=settings.AUTH_USER_MODEL)),
                ('work_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='workcenters.workcenter')),
            ],
            options={
                'ordering': ['mo', 'sequence'],
                'indexes': [models.Index(fields=['status'], name='manufacturi_status_305de3_idx'), models.Index(fields=['operator'], name='manufacturi_operato_1b0829_idx'), models.Index(fields=['work_center'], name='manufacturi_work_ce_d84d75_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='manufacturingorder',
            index=models.Index(fields=['status'], name='manufacturi_status_d15bf6_idx'),
        ),
        migrations.AddIndex(
            model_name='manufacturingorder',
            index=models.Index(fields=['scheduled_start_date'], name='manufacturi_schedul_ceb528_idx'),
        ),
        migrations.AddIndex(
            model_name='manufacturingorder',
            index=models.Index(fields=['assignee'], name='manufacturi_assigne_6a6d8a_idx'),
        ),
    ]
