# Generated by Django 4.2.23 on 2025-09-21 00:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('manufacturing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MOComponentRequirement',
            fields=[
                ('requirement_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_per_unit', models.DecimalField(decimal_places=2, help_text='Quantity of this component needed per unit of finished product', max_digits=10)),
                ('required_quantity', models.DecimalField(decimal_places=2, help_text='Total quantity required for this MO', max_digits=10)),
                ('consumed_quantity', models.DecimalField(decimal_places=2, default=0, help_text='Quantity already consumed/allocated', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mo_requirements', to='products.product')),
                ('mo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_requirements', to='manufacturing.manufacturingorder')),
            ],
            options={
                'ordering': ['component__name'],
                'unique_together': {('mo', 'component')},
            },
        ),
    ]
