# Generated by Django 4.2.23 on 2025-09-21 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0002_mocomponentrequirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='pause_start_time',
            field=models.DateTimeField(blank=True, help_text='When work was paused', null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='total_pause_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Total time paused in minutes'),
        ),
    ]
