# Generated by Django 4.2.24 on 2025-09-20 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Product name (e.g., 'Wooden Table', 'Screw')", max_length=150)),
                ('sku', models.CharField(help_text='Stock Keeping Unit or product code', max_length=50, unique=True)),
                ('product_type', models.CharField(choices=[('RAW_MATERIAL', 'Raw Material'), ('FINISHED_GOOD', 'Finished Good')], default='RAW_MATERIAL', max_length=20)),
                ('current_stock', models.DecimalField(decimal_places=2, default=0.0, help_text='Real-time available quantity in inventory', max_digits=10)),
                ('minimum_stock', models.DecimalField(decimal_places=2, default=0.0, help_text='Minimum stock level for alerts', max_digits=10)),
                ('unit_of_measure', models.CharField(default='units', help_text="e.g., 'units', 'kg', 'liters', 'meters'", max_length=20)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('description', models.TextField(blank=True, help_text='Product description or notes')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['product_type'], name='products_pr_product_cea9e6_idx'), models.Index(fields=['sku'], name='products_pr_sku_ca0cdc_idx')],
            },
        ),
    ]
