# Generated by Django 4.2.24 on 2025-09-20 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workcenters', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BOM',
            fields=[
                ('bom_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Descriptive name (e.g., 'Wooden Table Recipe V1')", max_length=150)),
                ('version', models.CharField(default='1.0', help_text='BOM version', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Only one active BOM per product')),
                ('description', models.TextField(blank=True, help_text='BOM description or notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_boms', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boms', to='products.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BOMOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Operation name (e.g., 'Assembly', 'Painting')", max_length=100)),
                ('sequence', models.PositiveIntegerField(help_text='Order of operations (1, 2, 3...)')),
                ('duration_minutes', models.PositiveIntegerField(help_text='Estimated time to complete (per unit)')),
                ('description', models.TextField(blank=True, help_text='Detailed operation instructions')),
                ('setup_time_minutes', models.PositiveIntegerField(default=0, help_text='One-time setup time')),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='bom.bom')),
                ('work_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workcenters.workcenter')),
            ],
            options={
                'ordering': ['sequence'],
                'unique_together': {('bom', 'sequence')},
            },
        ),
        migrations.CreateModel(
            name='BOMComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantity needed to make one unit of the finished product', max_digits=10)),
                ('notes', models.TextField(blank=True, help_text='Component-specific notes')),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='bom.bom')),
                ('component', models.ForeignKey(help_text='Raw material required', on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'ordering': ['component__name'],
                'unique_together': {('bom', 'component')},
            },
        ),
        migrations.AddIndex(
            model_name='bom',
            index=models.Index(fields=['product', 'is_active'], name='bom_bom_product_842e96_idx'),
        ),
        migrations.AddConstraint(
            model_name='bom',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('product',), name='unique_active_bom_per_product'),
        ),
    ]
